Repository lifeart/demo-ember-vite, pull requests merged in 2023-01, with the labels that each got.

#31 Remove repeated addon
  readme.md
Labels: documentation

#32 Ember simple auth
  compat/ember-simple-auth/use-session-setup-method.ts
  package.json
  src/addons/ember-simple-auth.ts
  src/addons/index.ts
  src/authenticators/custom.ts
  src/config/registry.ts
  src/controllers/application.ts
  src/controllers/login.ts
  src/router.ts
  src/routes/application.ts
  src/routes/login.ts
  src/routes/logout.ts
  src/routes/profile.ts
  src/templates/application.hbs
  src/templates/login.hbs
  src/templates/main.ts
  src/templates/profile.hbs
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#20 glint (not working)
  package.json
  readme.md
  src/config/registry.ts
  src/main.ts
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: help wanted

#43 Renamed `initializer` folder to plural name
  src/config/initializer.ts
  src/initializers/logger.ts
  src/instance-initializers/logger.ts
Labels: bug

#41 CLI
  blueprints/component/class.hbs
  blueprints/component/template.hbs
  blueprints/component/test.hbs
  blueprints/controller/class.hbs
  blueprints/controller/test.hbs
  blueprints/helper/class.hbs
  blueprints/helper/test.hbs
  blueprints/initializer/class.hbs
  blueprints/initializer/test.hbs
  blueprints/instance-initializer/class.hbs
  blueprints/instance-initializer/test.hbs
  blueprints/route/class.hbs
  blueprints/route/template.hbs
  blueprints/route/test.hbs
  blueprints/service/class.hbs
  blueprints/service/test.hbs
  blueprints/template/template.hbs
  blueprints/util/class.hbs
  blueprints/util/test.hbs
  package.json
  patches/ember-router-generator+2.0.0.patch
  plopfile.js
  tests/helpers/application.ts
  tests/index.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement
